namespaceRequests: []
  # - name: vault
  #   rbac:
  #    - role:
  #        name: vault
  #        kind: Role
  #        rules: []
  #      roleBinding:
  #        name: vault
  #        subjects:
  #          - kind: ServiceAccount
  #            name: vault

  #   memory: 256Mi
  # - name: grafana
  #   cpu: 100m



grafana:
  destination:
    name: hub
    namespace: grafana
  repository:
    repoURL: 'https://github.com/advatys/grafana.git'
    path: grafana-dashboards
    targetRevision: main
  config:
    dashboards: []
    folders: []
    datasources: []

vaultConfig:
  project: default
  destination:
    name: hub
    namespace: vault
  repository:
    repoURL: 'git@github.com:advatys/vaultaas.git'
    path: vault-config
    targetRevision: main
  config: {}

syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
  - ApplyOutOfSyncOnly=true