syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
  - ApplyOutOfSyncOnly=true


vaultConfig:
  destination:
    name: hub
    namespace: vault
  repository:
    repoURL: 'https://github.com/advatys/vaultaas.git'
    path: vault-config
    targetRevision: main
  config: {}

ciPipelineRBAC:
  create: true
