instanceName: ""
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
  - ApplyOutOfSyncOnly=true


mainApp:
  destinations:
   - name: hub

  sourceRepos:
    - '*'

grafanaDashboards:
  destination:
    name: hub
    namespace: grafana
  repository:
    repoURL: 'https://github.com/onehq/grafana.git'
    path: grafana-dashboards
    targetRevision: main
  config:
    dashboards: []

vaultConfig:
  destination:
    name: hub
    namespace: vault
  repository:
    repoURL: 'https://github.com/onehq/vaultaas.git'
    path: vault-config
    targetRevision: main
  config: {}

extraApps: []

ciPipelineRBAC:
  create: true
