# TODO: to be replaced by NamespaceRequest
{{- range .Values.mainApp.destinations }}
kind: Namespace
apiVersion: v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: {{ .namespace }}
---
{{- end }}