# TODO: to be replaced by NamespaceRequest
{{- if .Values.ciPipelineRBAC.create }}
kind: Namespace
apiVersion: v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  name: {{ .Values.instanceName }}-cd
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.instanceName }}-ci-pipeline
  namespace: {{ .Values.instanceName }}-cd
  labels:
    {{- include "cd-preconfig.labels" . | nindent 4 }}

subjects:
  - kind: ServiceAccount
    name: {{ .Values.instanceName }}-ci-pipeline
    namespace: {{ .Values.instanceName }}-ci-pipeline

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.instanceName }}-ci
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.instanceName }}-ci-pipeline
  namespace: {{ .Values.instanceName }}-cd
  labels:
    {{- include "cd-preconfig.labels" . | nindent 4 }}
rules:
  - verbs:
      - create
      - update
      - patch
      - get
      - list
      - watch
    apiGroups:
      - argoproj.io
    resources:
      - applications
{{- end }}